# Generated by Django 6.0.2 on 2026-08-13 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_cloudstoragetoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fileoperation',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the operation (null for legacy/system rows)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_operations', to=settings.AUTH_USER_MODEL),
        ),
    ]
