# Generated by Django 6.0.2 on 2026-08-13 05:05

import manager.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_fileoperation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudstoragetoken',
            name='access_token',
            field=manager.fields.EncryptedTextField(help_text='OAuth 2.0 access token (encrypted at rest)'),
        ),
        migrations.AlterField(
            model_name='cloudstoragetoken',
            name='refresh_token',
            field=manager.fields.EncryptedTextField(blank=True, default='', help_text='OAuth 2.0 refresh token (encrypted at rest)'),
        ),
    ]
