# Generated by Django 6.0.2 on 2026-08-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_cloudstoragetoken_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileoperation',
            name='operation',
            field=models.CharField(choices=[('UPLOAD', 'Upload'), ('DOWNLOAD', 'Download'), ('RENAME', 'Rename'), ('DELETE', 'Delete'), ('MOVE', 'Move')], help_text='Type of file operation', max_length=20),
        ),
    ]
