# Generated by Django 6.0.2 on 2026-08-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_fileoperation_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dry_run', models.BooleanField(default=False, help_text='True if the plan was only simulated')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the run started')),
                ('finished_at', models.DateTimeField(blank=True, help_text='When the run finished (null while running)', null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', help_text='Run status', max_length=10)),
                ('pushed', models.IntegerField(default=0, help_text='Files copied local -> S3')),
                ('pulled', models.IntegerField(default=0, help_text='Files copied S3 -> local')),
                ('failed_count', models.IntegerField(default=0, help_text='Files that failed to copy')),
                ('error_message', models.TextField(blank=True, default='', help_text='Fatal error message if the run failed')),
            ],
        ),
    ]
